---
- hosts: all
  connection: local
  become: true
  pre_tasks:
  - name: pre | update packages (Debian, Ubuntu)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution in ["Debian", "Ubuntu"]
    changed_when: false

- hosts: workstations
  connection: local
  become: true
  profiles:
  - profile: base
  - profile: workstation

