---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  #
  # Make sure packages are updated
  #
  - name: pre | touch /tmp/ansible.txt to reflect run time
    ansible.builtin.file:
      path: /tmp/ansible.txt
      state: touch
      mode: u=rw,g=r,o=r
    changed_when: false

  - name: pre | update packages (Debian, Ubuntu)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution in ["Debian", "Ubuntu"]
    changed_when: false

  tasks:
  - name: ensure qemu-guest-agent installed on QEMU guests
    block:
    - name: ensure qemu-guest-agent installed
      package:
        name: qemu-guest-agent
        state: present
    - name: ensure qemu-guest-agent service started
      service:
        name: qemu-guest-agent
        state: started
    when: ansible_system_vendor == 'QEMU'

  #
  # ansible-pull support tasks
  #
  # - name: ensure ansible_puller cron job created
  #   cron:
  #     name: ansible auto-provision
  #     user: ansible
  #     minute: "*/10"
  #     job: ansible-pull -o -U https://github.com/CoolpeopleNetworks/Provision.git

#
# Workstations
#
- hosts: workstations
  connection: local
  become: true
  roles:
  - role: base
  - role: workstation

#
# Servers
#
- hosts: servers
  connection: local
  become: true
  roles:
  - role: base
  - role: server

#
# Nextcloud Instances
#
- hosts: nextcloud
  connection: local
  become: true
  roles:
  - role: nextcloud_server

#
# Headscale Instances
#
- hosts: headscale
  connection: local
  become: true
  vars:
    headscale_server_url: https://headscale.coolpeople.io:8443
    headscale_version: 0.22.3
    headscale_arch: amd64
    headscale_listen_addr: 0.0.0.0:8443

  roles:
  - role: headscale_server

#
# Gitlab Hosts
#
- hosts: gitlab_hosts
  connection: local
  become: true
  vars:
    gitlab_url: https://gitlab.coolpeople.io
    gitlab_version: 16.4.1-ee.0
  roles:
  - role: gitlab_server

#
# Postgresql Hosts
#
- hosts: postgresql_hosts
  connection: local
  become: true
  tasks:
  - name: ensure postgresql package installed
    package:
      name: 
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
      state: present

  - name: "ensure postgresql service started and enabled"
    service: 
      name: postgresql
      state: started
      enabled: yes

  # - name: "ensure admin database user created"
  #   postgresql_user:
  #     state: present
  #     name: "admin"
  #     password: "bonky123"
  #   become: yes
  #   become_user: postgres

  # - name: "ensure admin database user has access to postgresql"
  #   postgresql_privs:
  #     type: database
  #     database: "postgres"
  #     roles: "admin"
  #     grant_option: no
  #     privs: all
  #   become: yes
  #   become_user: postgres

  - name: "ensure host access for admin is allowed"
    postgresql_pg_hba:
      dest: "/etc/postgresql/14/main/pg_hba.conf"
      contype: host
      source: 10.10.0.0/16
      databases: all
      method: password
      users: all
      create: true
    become: yes
    become_user: postgres
    notify: restart postgres

  - name: Configure PostgreSQL. Set listen_addresses.
    lineinfile: 
      dest: /etc/postgresql/14/main/postgresql.conf
      regexp: "listen_addresses =" 
      line: "listen_addresses = '*'" 
      state: present
    become: yes
    become_user: postgres
    notify: restart postgres

  handlers:
  - name: restart postgres
    service: name=postgresql state=restarted

- hosts: k8s_prod
  roles:
  - role: ansible-keepalived
    become: true
    vars:
      keepalived_instances:
        internal:
          interface: "{{ vrrp_nic | default(ansible_default_ipv4.interface, true) }}"
          state: "{{ (groups['k8s_prod'].index(inventory_hostname) == 0) | ternary('MASTER','BACKUP') }}"
          virtual_router_id: "{{ virtual_router_id }}"
          priority: "{{ (inventory_hostname == groups['k8s_prod'][0]) | ternary('250', '100') }}"
          vips:
          - "{{ virtual_ip }} dev {{ vrrp_nic | default(ansible_default_ipv4.interface, true) }}"

  - role: ansible_role_netdata
    vars:
      netdata_claim_rooms: 11ff9a75-358b-472a-97c5-f82bc8afd82c
      netdata_claim_token: t6Ku6wbRh6JnwQRRDhkTFUBiBePsYmxDTGMOWPytkMbYgtx0FZZwF5zgxCIImxTuOfvio08TtUqa9ZHPCMyxEoGajP6UWjFB9zSfVpTjkV4HJK8pKTJ3ixhreQ8emrm3EqGfRS0

  - role: ansible_role_microceph
    become: true
    vars:
      microceph_cluster_nodes: k8s_prod
      microceph_seed_node: r720xd-1
      microceph_encrypt_data: False
      microceph_replicate_count: 3

  - role: ansible_role_microk8s
    become: true
    vars:
      microk8s_version: 1.30/stable
      microk8s_enable_HA: true
      microk8s_group_HA: k8s_dev
      microk8s_plugins:
        community: true
        dns: "1.1.1.1"
        helm: true
        helm3: true
        hostpath-storage: false
        istio: false
        ingress: true
        registry: true
        rook-ceph: true
        cert-manager: true
        metallb: "10.10.202.1-10.10.202.254"

  tasks:
  - name: Ensure required packages installed
    become: true
    ansible.builtin.apt:
      pkg:
      - btop
      - tmux
      - lsscsi

  - name: Ensure kubectl config created
    become: true
    ansible.builtin.shell: microk8s config > ~/.kube/config
    changed_when: false

  # - name: Ensure everestctl is installed
  #   become: true
  #   ansible.builtin.get_url:
  #     url: https://github.com/percona/everest/releases/latest/download/everestctl-linux-amd64
  #     dest: /usr/local/bin/everestctl
  #     mode: '0555'

- hosts: r720xd-1
  become: true            
  tasks:
  - name: Get a list of existing storage classes
    ansible.builtin.shell: microk8s kubectl get --no-headers storageclasses.storage.k8s.io
    register: existing_ceph_rbd_storage_class
    changed_when: False
    ignore_errors: True

  - name: Ensure Microceph and MicroK8s are connected
    ansible.builtin.shell: microk8s connect-external-ceph
    register: microceph_microk8s_connect
    when: "'ceph-rbd' not in existing_ceph_rbd_storage_class.stdout"

  - name: Ensure Microceph is the default K8s storage class
    ansible.builtin.shell: |
      kubectl patch storageclass ceph-rbd -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
    when: "'(default)' not in existing_ceph_rbd_storage_class.stdout"

  # - name: Get the status of the Everest rollout (if any)
  #   ansible.builtin.shell: |
  #     kubectl -n everest-system rollout status deployment/percona-everest || true
  #   register: everest_rollout_status
  #   changed_when: false

  # - name: Ensure Everest installed in cluster
  #   ansible.builtin.shell: |
  #     everestctl install --namespaces percona-everest --operator.mongodb=true --operator.postgresql=true --operator.xtradb-cluster=true --skip-wizard
  #   when: "'successfully rolled out' not in everest_rollout_status.stdout"
