---
- name: ensure headscale package has been downloaded
  ansible.builtin.get_url:
    url: "https://github.com/juanfont/headscale/releases/download/v{{headscale_version}}/headscale_{{headscale_version}}_linux_{{headscale_arch}}.deb"
#         https://github.com/juanfont/headscale/releases/download/v0.22.3/headscale_0.22.3_linux_amd64.deb
    dest: /usr/share/v{{headscale_version}}/headscale_{{headscale_version}}_linux_{{headscale_arch}}.deb
    mode: '0440'
  register: headscale_package_downloaded

- name: ensure headscale deb package installed
  ansible.builtin.apt:
    deb: /usr/share/v{{headscale_version}}/headscale_{{headscale_version}}_linux_{{headscale_arch}}.deb

