---
- name: ensure headscale package has been downloaded
  ansible.builtin.get_url:
    url: "https://github.com/juanfont/headscale/releases/download/v{{headscale_version}}/headscale_{{headscale_version}}_linux_{{headscale_arch}}.deb"
    dest: "/usr/share/headscale_{{headscale_version}}_linux_{{headscale_arch}}.deb"
    mode: '0440'
  register: headscale_package_downloaded

- name: ensure headscale deb package installed
  ansible.builtin.apt:
    deb: "/usr/share/headscale_{{headscale_version}}_linux_{{headscale_arch}}.deb"

