---
- name: install packages
  package:
    name:
    - tmux
    - htop

- name: install packages specific to Ubuntu minimal
  package:
    name:
    - inetutils-ping
    - inetutils-traceroute
  when: ansible_distribution == "Ubuntu"
