---
- name: ensure couchdb repository installed
  ansible.builtin.apt_repository:
    repo: "deb https://apache.jfrog.io/artifactory/couchdb-deb/ {{ansible_distribution_release}} main"
    state: present

- name: ensure couchdb installed
  ansible.builtin.apt:
    name: coucndb
    state: present
    update_cache: true
