---
- name: add couchdb PPA repository
  become: yes
  apt_repository:
    repo: ppa:couchdb/stable

- name: install couchdb
  become: yes
  apt:
    name: couchdb
  register: couchdb_install

- name: stop couchdb
  become: yes
  service:
    name: couchdb
    state: stopped
  when: couchdb_install.changed
